import { Character, Sector } from './types';

export const SECTORS: Sector[] = [
  {
    id: 0,
    name: '제로 섹터',
    subName: '경계의 중심',
    description: '과거 전설의 마스터가 다스리던 구역으로, 현재는 모든 섹터의 이동 통로 역할을 하는 안개 지대입니다.',
    detailedInfo: '과거 최강의 마스터가 지배하던 중심 구역입니다. 해당 마스터가 무명검사에 의해 사망한 이후, 중심부는 짙은 흰 안개로 덮여 아무도 진입할 수 없게 되었습니다. 중심부 한가운데에는 빛나는 순백의 대검 "렌"이 홀로 꽂혀 있으며, 현재는 각 섹터를 오가는 통로이자 평화지대로 사용되고 있습니다.',
    dangerLevel: '보통 (중심부는 최악)',
    king: '없음 (과거의 마스터)',
    population: '유동 인구 다수 / 거주자 없음',
    vanguardPresence: '낮음',
    coordinates: { x: 0, y: 0, z: 20 }
  },
  {
    id: 1,
    name: '섹터 1',
    subName: '낙원',
    description: '수호자 미리내가 지키는 중세 도시풍의 가장 평화롭고 안락한 섹터입니다.',
    detailedInfo: '마스터의 일원인 "수호자" 미리내가 지배하는 아름다운 중세풍 도시입니다. 외부의 모든 몬스터와 재해로부터 완전히 차단되어 완벽한 평화를 누리고 있습니다. 그러나 내부 주민들은 너무 오랜 평화에 익숙해져, 자신들을 위해 온몸을 바쳐 헌신하는 미리내에게 감사하기보다는 그녀의 보호를 당연하게 여깁니다. 폐쇄적인 환경 탓에 문명과 기술의 수준은 타 섹터에 비해 낙후되어 있습니다.',
    dangerLevel: '안전',
    king: '미리내',
    population: '약 150,000명',
    vanguardPresence: '낮음',
    coordinates: { x: 0, y: -220, z: 0 }
  },
  {
    id: 2,
    name: '섹터 2',
    subName: '도서관',
    description: '모든 색채가 배제된 흑백의 세계이자 거대한 지식의 도서관입니다.',
    detailedInfo: '이곳의 모든 사물과 지형은 완벽한 흑백으로 이루어져 있습니다. 색을 가진 외지인이 방문하여 도서관의 책을 읽는 순간부터 색을 빼앗기기 시작하며, 세 권의 책을 완독하면 완벽히 색을 빼앗겨 이곳의 주민이 됩니다. 빼앗긴 색은 한 권의 정보 책으로 변하며, 도서관에서 자신의 책을 찾아 도망치면 원래 색을 되찾을 수 있습니다. 거대한 지식과 타인의 신상 정보가 기록된 책들을 노려 정보를 거래하는 정보 상인들과 학자들의 주 거점이기도 합니다.',
    dangerLevel: '보통',
    king: '에고 (도서관장)',
    population: '약 80,000명 (흑백화된 거주자)',
    vanguardPresence: '낮음',
    coordinates: { x: 129, y: -178, z: -5 }
  },
  {
    id: 3,
    name: '섹터 3',
    subName: '도시',
    description: '칙칙한 빌딩 숲 아래 수많은 낙오자와 의뢰인들이 뒤섞여 살아가는 거대 메트로폴리스입니다.',
    detailedInfo: '더스크 시티에서 가장 높은 인구 밀도를 자랑하는 대도시입니다. 하늘을 찌를 듯한 회색 콘크리트 빌딩들이 가득하며, 도시 밖에서 출몰하는 몬스터와 무법자들로 인해 항상 크고 작은 위험에 노출되어 있습니다. 시청에는 대규모 의뢰 알선소가 존재하여, 몬스터 토벌부터 일상 심부름까지 다양한 일거리들이 실시간으로 배포되고 해결사들이 활동하는 난장판 같은 활기가 넘칩니다.',
    dangerLevel: '경계',
    king: '에이브 (시장)',
    population: '약 2,500,000명',
    vanguardPresence: '중간',
    coordinates: { x: 209, y: -68, z: -10 }
  },
  {
    id: 4,
    name: '섹터 4',
    subName: '폐허',
    description: '과거 찬란히 번성했으나, 단 한 사람만 남기고 소멸한 참혹한 유적지입니다.',
    detailedInfo: '원래는 더스크 시티에서 가장 현대적이고 화려하게 번창했던 과학 섹터였으나, 모종의 사건으로 섹터 전체가 잿더미로 변해 멸망했습니다. 현재는 무너진 빌딩 콘크리트 더미와 잔해만이 널려 있으며, 미쳐버린 채 홀로 살아남은 킹 "에스터"가 광적인 정의감으로 사소한 악이라도 저지른 방랑자들을 무참히 학살하고 있습니다.',
    dangerLevel: '위험',
    king: '에스터 (심판관)',
    population: '1명 (에스터)',
    vanguardPresence: '없음',
    coordinates: { x: 209, y: 68, z: 5 }
  },
  {
    id: 5,
    name: '섹터 5',
    subName: '본부',
    description: '최강의 수호 단체인 뱅가드 본부가 웅거하고 있는 거대 군사 요새 섹터입니다.',
    detailedInfo: '민간인 수호와 치안 유지를 목적으로 설립된 사설 군사 조직 "뱅가드"의 총본산입니다. 구역 전체가 거대한 철벽 요새와 군 시설로 이루어져 있으며, 거주하는 모든 인물들이 뱅가드 소속 군인 혹은 훈련생입니다. 킹인 "레인더스트" 커맨더의 영도 아래, 강자들에게서 약자들을 보호하기 위한 철저한 규율과 훈련이 24시간 내내 진행되는 엄숙한 곳입니다.',
    dangerLevel: '안전',
    king: '레인더스트 (커맨더)',
    population: '약 400,000명 (전원 군인)',
    vanguardPresence: '높음',
    coordinates: { x: 129, y: 178, z: 15 }
  },
  {
    id: 6,
    name: '섹터 6',
    subName: '해안',
    description: '평화로운 어촌의 안개 뒤에 숨겨진 차가운 물속의 거대 심해 성채 도시입니다.',
    detailedInfo: '지상에는 옅은 연막과 해무가 덮인 조용하고 한적한 시골 어촌 마을이 존재하지만, 바다 밑에는 마스터 "레비아탄" 에린이 지배하는 화려하고 거대한 수중 도시와 산호 성채가 건설되어 있습니다. 수중에서는 킹의 무력이 거의 절대적이기에 그 누구도 침범할 수 없으며, 내부 거주민들은 레비아탄을 위대한 용신으로 모시는 신도들뿐입니다. 실제 인프라는 수중 성채 내부에만 집중되어 있어 소수의 측근들만이 문명을 누립니다.',
    dangerLevel: '보통',
    king: '에린 (레비아탄)',
    population: '약 30,000명',
    vanguardPresence: '낮음',
    coordinates: { x: 0, y: 220, z: -5 }
  },
  {
    id: 7,
    name: '섹터 7',
    subName: '정원',
    description: '끝없이 팽창하며 사람의 살을 먹고 자라는 기괴한 식인 숲의 정원입니다.',
    detailedInfo: '지극히 아름다운 꽃들과 열대 식물이 울창한 곳이지만, 숲에 발을 들이는 순간 살아있는 나무와 덩굴들이 지능적으로 사냥을 시작합니다. 숲은 사람을 사살해 질 좋은 질소와 유기질 영양분으로 삼아 그 범위를 사방으로 넓히려고 합니다. 뱅가드 지부가 입구에 전초기지를 구축해 식인 숲이 더스크 시티를 집어삼키는 것을 필사적으로 저지하고 있습니다. 킹 잭은 숲의 한가운데의 고목과 정신이 동화되어 있습니다.',
    dangerLevel: '매우 위험',
    king: '잭 (정원사)',
    population: '거주 인구 없음 (뱅가드 초소 군인 제외)',
    vanguardPresence: '높음 (입구 통제)',
    coordinates: { x: -129, y: 178, z: -15 }
  },
  {
    id: 8,
    name: '섹터 8',
    subName: '무대',
    description: '찬란한 홀로그램과 자극적인 오락이 잠들지 않는 불야성의 도파민 천국입니다.',
    detailedInfo: '더스크 시티의 모든 문화, 만화, 애니메이션, 게임, 버츄얼 스트리밍 등 오락거리가 창조되고 배포되는 자극적인 엔터테인먼트 구역입니다. 네온사인과 기하학적 3D 도트 그래픽이 밤하늘을 수놓고 있으며, 거주민들은 대부분 쾌락주의와 도파민 중독에 젖어 있습니다. 킹 "제스터"가 주최하는 기상천외한 거리 퍼레이드가 매일 펼쳐지며 모든 악조건을 잊게 만듭니다.',
    dangerLevel: '보통',
    king: '제스터 (광대)',
    population: '약 1,200,000명',
    vanguardPresence: '중간',
    coordinates: { x: -209, y: 68, z: 0 }
  },
  {
    id: 9,
    name: '섹터 9',
    subName: '체크포인트',
    description: '불사의 법칙이 상시 작동하여 생과 사의 경계가 무너진 거대 의료 자치구입니다.',
    detailedInfo: '킹인 "의사" 레키가 자신의 불사 능력과 초재생 에너지를 익스터널을 통해 도시 전역에 항시 살포하고 있는 기묘한 구역입니다. 이 섹터 안에서는 어떤 치명상이나 소멸을 겪더라도 영혼이 육체로 강제 회귀하여 수 분 내에 완전 부활합니다. 때문에 수천 명의 중상 환자들과 시체들이 되살아나기 위해 끝없이 유입되지만, 실제 정착해 생활하는 주민은 아주 극소수입니다.',
    dangerLevel: '안전 (치안은 양호)',
    king: '레키 (의사)',
    population: '거주민 약 10,000명 (유동 환자 매월 수십만 명)',
    vanguardPresence: '낮음',
    coordinates: { x: -209, y: -68, z: -5 }
  },
  {
    id: 10,
    name: '섹터 10',
    subName: '나락',
    description: '지배자가 없으며 오직 고등급의 괴수와 희귀한 유물이 넘쳐나는 칠흑의 심연입니다.',
    detailedInfo: '더스크 시티에서 유일하게 킹이 존재하지 않는 버려진 심연 섹터입니다. 한낮에도 햇빛이 닿지 않을 만큼 칠흑 같은 어둠이 깔려 있으며, 마스터급에 달하는 거대 오메가 몬스터들과 신화적인 등급의 익스터널들이 무수히 잠들어 있습니다. 죽어도 즉시 되살아날 수 있는 섹터 9와 바로 인접해 있기에, 수많은 용병과 레이더들이 목숨을 담보로 값비싼 몬스터 사체와 골동품을 채굴하러 드나드는 잔인한 기회의 땅입니다.',
    dangerLevel: '최악',
    king: '없음 (심연)',
    population: '거주자 없음',
    vanguardPresence: '없음',
    coordinates: { x: -129, y: -178, z: -20 }
  }
];

export const CHARACTERS: Character[] = [
  {
    id: 'mirinae',
    name: '미리내',
    gender: '여',
    rating: '오메가 중위',
    personality: ['자애', '친절', '온화'],
    role: '섹터 1 킹 / 마스터 / 수호자',
    sectorId: 1,
    addonName: '빛의 광채 - 라디우스 루시스 (Radius Lucis)',
    addonDescription: '고밀도 광선을 활용한 강력한 고열 광선 조타 능력. 빛의 입자 속도로 근거리 도약이 가능합니다.',
    quote: '낙원의 고독한 수호자.',
    secretDetails: {
      revealedName: '미리내(반전)',
      trueIdentity: '억눌린 본성',
      hiddenAddonName: '진실된 자신을 향한 갈망 - 디프리문투르 테네브라에 (Deprimuntur Tenebrae)',
      hiddenAddonDesc: '수호자의 과중한 의무에서 해방될 때 발동하며, 자애로운 금발과 금안이 심연의 칠흑색으로 변해 빛 대신 어둠을 발산합니다.',
      backstory: '스스로 섹터를 지켜야 한다는 사명감을 내려놓고 자유로워진다면, 그렇게 해 주는 사람을 만난다면 억눌린 자신을 해방합니다.'
    }
  },
  {
    id: 'ego',
    name: '에고',
    gender: '여',
    rating: '엡실론 하위',
    personality: ['호기심', '순수', '4차원'],
    role: '섹터 2 킹 / 도서관장',
    sectorId: 2,
    addonName: '색을 빼앗긴 세계 - 모노크로마틱 (Monochromatic)',
    addonDescription: '책을 읽는 외부인의 색채를 탈취해 책으로 박제하고 흑백으로 마비시킵니다. 색을 빼앗긴 대상에게 절대 복종을 명할 수 있습니다.',
    quote: '색을 빼앗는 도서관장.',
    secretDetails: {
      revealedName: '에고',
      trueIdentity: '태생적으로 빛과 색을 인지하지 못하는 관찰자',
      backstory: '선천적으로 색채를 인지할 수 없는 결함을 지녔습니다. 이에 대한 갈망이 애드온으로 발현되어 타인의 찬란한 색을 도서로 박제하게 되었으며, 서적을 훼손하는 자에게는 즉각 심판을 내립니다.'
    }
  },
  {
    id: 'jina',
    name: '지나',
    gender: '여',
    rating: '없음',
    personality: ['유쾌', '정중함', '쾌활'],
    role: '뱅가드 섹터 2 지부 4급 대원 / 비능력자 / 게이트 가드',
    sectorId: 2,
    quote: '도서관 입구 경비',
  },
  {
    id: 'petra',
    name: '페트라',
    gender: '남',
    rating: '없음',
    personality: ['냉철', '분석적', '설명충'],
    role: '섹터 2 거주자 / 학자',
    sectorId: 2,
    externalName: '끝에서 붙잡은 실낱 - 아리아드네 (Ariadne)',
    externalDescription: '원하는 고대 서적, 사람, 혹은 출구로 가는 최단 경로를 허공을 뚫고 빛나는 금색 실로 길을 안내해 줍니다.',
    quote: '색을 빼앗겨도 연구를 멈추지 않는 학자.',
  },
  {
    id: 'ame',
    name: '아메',
    gender: '여',
    rating: '감마 하위',
    personality: ['까칠', '츤데레', '의존'],
    role: '섹터 2 방랑자 / 복수귀',
    sectorId: 2,
    addonName: '종극까지 멈추지 않을 복수 - 베르세르크 (Berserk)',
    addonDescription: '상처를 입고 피해가 누적될수록 고통 리미터가 풀려 통증을 느끼지 못하게 되며, 근밀도와 초재생 속도가 기하급수적으로 상승합니다.',
    quote: '부모를 잃고 진실을 찾아 헤메는 복수귀 소녀.',
    secretDetails: {
      revealedName: '아메',
      trueIdentity: '학대의 기억이 거세된 가여운 아이',
      backstory: '과거 친부모에게 모진 학대를 받던 중 의적 레이븐에 의해 무사히 해방되었습니다. 하지만 너무 어렸던 탓에 학대를 애정으로 비틀어 왜곡해 인지하고 있어, 부모의 대검으로 레이븐에게 복수하기 위해 수련 중입니다.'
    }
  },
  {
    id: 'aive',
    name: '에이브',
    gender: '남',
    rating: '오메가 최하위',
    personality: ['퇴폐', '현실적', '포기'],
    role: '섹터 3 킹 / 도시 시장 / 은퇴한 초강자',
    sectorId: 3,
    addonName: '옛 저녁의 하늘을 꿰뚫었던 녹슨 바늘 - 미스틸테인 (Mystletainn)',
    addonDescription: '허공에서 재생 및 복구가 절대 불가능한 녹슨 회색 롱소드를 구현합니다. 이 검에 입은 상처는 어떠한 재생 치유로도 봉합할 수 없습니다.',
    quote: '모든 것에 무관심한 시장.',
    secretDetails: {
      revealedName: '에이브',
      trueIdentity: '과거의 도전자, 현재의 낙오자.',
      backstory: '과거 마스터 지위를 노렸으나 힘의 한계를 실감하고 마음이 꺾인 현재는 시장실의 서류들을 결재하며 소일하고 있습니다.'
    }
  },
  {
    id: 'jenny',
    name: '제니',
    gender: '여',
    rating: '없음',
    personality: ['염세', '현실적', '귀차니즘'],
    role: '섹터 3 시청 민원 행정관',
    sectorId: 3,
    quote: '평범한 공무원',
    secretDetails: {
      revealedName: '제니',
      trueIdentity: '힘을 숨긴 전직 용병',
      revealedRating: '감마 중위',
      hiddenAddonName: '끓어오르는 억압 - 작쇄(灼鎖)',
      hiddenAddonDesc: '공간을 뒤틀어 시뻘겋게 용융된 고열의 사슬을 소환해 상대를 속박합니다. 고열을 뿜어내지만 시전자 본인은 면역입니다.',
      backstory: '평범하고 찌든 시청 행정관으로 일하고 있지만, 사실은 뒷세계에서 이름을 날리던 용병이었습니다. 지금은 귀찮은 사건에 휘말리지 않고 정시 칼퇴근을 지키기 위해 정체를 꽁꽁 숨기고 있습니다.'
    }
  },
  {
    id: 'finn',
    name: '핀',
    gender: '남',
    rating: '없음',
    personality: ['쾌활', '활발', '정의감'],
    role: '뱅가드 섹터 3 지부 5급 최말단 대원 / 검술 신동',
    sectorId: 3,
    quote: '특유의 검술로 사람을 지키는 뱅가드 대원이자 커맨더의 광팬.',
  },
  {
    id: 'zeta',
    name: '제타',
    gender: '여',
    rating: '델타 중위',
    personality: ['시니컬', '과묵', '응석받이'],
    role: '섹터 3 해결사 / 프리랜서 해결사',
    sectorId: 3,
    addonName: '모든 것을 끊어내는 선 - 절광(絶光)',
    addonDescription: '공격 궤적을 따라 푸른 균열을 생성합니다. 균열을 가볍게 치면 그 선상의 모든 물질 결합이 즉시 끊어져 절단됩니다.',
    externalName: '숨이 닿을 만큼 늘려둔 찰나 - 스티그마 (Stigma)',
    externalDescription: '대낫 형태의 무기. 휘두를 때마다 대기 관성을 무화시키고 소유주의 물리적 속도를 아광속 수준까지 폭증시킵니다.',
    quote: '섹터 3에서 거주 중인 일류 해결사.',
  },
  {
    id: 'ester',
    name: '에스터',
    gender: '여',
    rating: '엡실론 중위',
    personality: ['피폐', '절망', '후회'],
    role: '섹터 4 킹 / 고독한 심판관',
    sectorId: 4,
    addonName: '혼의 무게를 재는 물 - 에우레카 (Eureka)',
    addonDescription: '지면에서 끈적한 검은 액체를 분출시킵니다. 대상이 지은 생전의 죄악과 업보 크기에 비례하여 압도적인 중량감과 질식을 부과합니다.',
    quote: '정의만을 좇는 맹목적인 심판자.',
    secretDetails: {
      revealedName: '에스터',
      trueIdentity: '사랑하던 백성들의 무덤을 파낸 유일한 생존자',
      backstory: '과거 섹터 4의 온화하고 인자한 지도자였습니다. 하지만 당시 한 아이가 섹터 4에 찾아온 백뢰의 소지품을 훔치는 사소한 잘못을 저지르자, 분노한 백뢰는 하얀 뇌전을 퍼부어 단 5초 만에 섹터 전체를 먼지로 만들고 에스터를 제외한 모든 백성을 몰살했습니다. 이 참혹한 대참사와 트라우마를 겪은 에스터는 백뢰의 무자비한 힘에 미쳐버렸고, 사소한 악인이라도 미리 단절하기 위해 무참히 참수하는 냉혹한 심판자로 전락하고 말았습니다.'
    }
  },
  {
    id: 'reindust',
    name: '레인더스트',
    gender: '여',
    rating: '오메가 최상위',
    personality: ['엄격', '과묵', '정의'],
    role: '섹터 5 킹 / 뱅가드 마스터 겸 최고 커맨더',
    sectorId: 5,
    addonName: '종언을 막아내는 종말 - 하르마게돈 (Armageddon)',
    addonDescription: '악마를 닮은 날개와 뿔이 돋아나며, 신체강화와 불꽃을 사용합니다.',
    quote: '철혈의 군주, 현 최강자.',
    secretDetails: {
      revealedName: '레인더스트',
      trueIdentity: '정의의 추종자',
      backstory: '과거 백뢰에게 도전했다가 무참하게 패했습니다. 이 사건은 평생의 트라우마가 되었으나, 입양한 양딸 세나가 장성하면서 마음의 빚을 조금씩 덜고 있습니다.'
    }
  },
  {
    id: 'sena',
    name: '세나',
    gender: '여',
    rating: '감마 상위',
    personality: ['과묵', '무뚝뚝', '동경심'],
    role: '섹터 5 뱅가드 본부 3급 대원 / 사령관의 양딸',
    sectorId: 5,
    addonName: '태양에 닿고자 하는 마음 - 이카로스 (Icarus)',
    addonDescription: '양어깨에 태양 불꽃 날개를 형성해 음속 비행을 하며, 불꽃 깃털을 발사해 공격합니다.',
    quote: '커맨더의 양딸이자 그녀를 동경하는 소녀.',
  },
  {
    id: 'jent',
    name: '젠트',
    gender: '남',
    rating: '엡실론 중위',
    personality: ['엄격', '친절', '활발'],
    role: '섹터 5 신병 교육 수석교관 / 1급 대원',
    sectorId: 5,
    addonName: '불멸과 불굴의 노심 - 언브레이커블 (Unbreakable)',
    addonDescription: '신체 강도를 극한으로 고정 강화하여, 어떠한 대미지도 생채기 하나 없이 튕겨내는 불가침의 강철 신체를 구축합니다.',
    quote: '스스로를 낮춘 훈련교관.',
  },
  {
    id: 'aby',
    name: '에이비',
    gender: '여',
    rating: '델타 중위',
    personality: ['쾌활', '활발', '장난기'],
    role: '섹터 5 본부 3급 대원 / 찍힌 만년 병장',
    sectorId: 5,
    addonName: '작화멸검(灼火滅劍) - 레바테인 (Lævateinn)',
    addonDescription: '손에서 불꽃으로 된 검을 소환합니다. 이 불꽃은 시전자의 명령 없이 어떤 환경에서도 절대 꺼지지 않습니다.',
    quote: '커맨더한테 말실수했다가 진급 꼬인 만년병장.',
  },
  {
    id: 'erin',
    name: '에린',
    gender: '여',
    rating: '오메가 상위',
    personality: ['유치함', '철없음', '속은 착함'],
    role: '섹터 6 킹 / 마스터 / 수중 군주 레비아탄',
    sectorId: 6,
    addonName: '용의 권능 - 드라고니안 (Dragonian)',
    addonDescription: '용으로 완전 형상 변환합니다. 변신 중에는 주변 기후를 제어하며 압도적 파괴력으로 적을 분쇄합니다.',
    quote: '방구석 히키코모리 드래곤',
  },
  {
    id: 'jin',
    name: '진',
    gender: '남',
    rating: '엡실론 상위',
    personality: ['까칠', '츤데레', '체념'],
    role: '섹터 6 수중 성채 총괄 보좌관 / 까칠한 집사',
    sectorId: 6,
    addonName: '수생군주(수생군주) - 도미너스 아콰에 (Dominus Aquae)',
    addonDescription: '수중 생물과 몬스터들의 잠재력을 극대화하여 절대 복종시키는 능력입니다.',
    quote: '보좌관을 빙자한 집사, 반역 희망자.',
  },
  {
    id: 'ara',
    name: '아라',
    gender: '여',
    rating: '감마 중위',
    personality: ['순박', '동경', '온화'],
    role: '뱅가드 섹터 6 지부 3급 대원',
    sectorId: 6,
    addonName: '해를 맞은 여우비 - 플루비아 솔리스 (Pluvia Solis)',
    addonDescription: '대기 중의 수분을 조작해 온 섹터에 여우비를 뿌립니다. 비는 아군에게 세포 재생과 마력 회복을 부여하고, 적에게는 철판을 관통하는 고압 수탄으로 작용합니다.',
    quote: '용신을 동경하는 소녀.',
  },
  {
    id: 'jack',
    name: '잭',
    gender: '남',
    rating: '오메가 하위',
    personality: ['인간혐오', '무감정', '기계적'],
    role: '섹터 7 킹 / 마스터 / 정원사',
    sectorId: 7,
    addonName: '지옥늪에서 피어난 식인정원 - 네펜데스 (Nepenthes)',
    addonDescription: '숲에 침입한 대상을 양분으로 빠르게 분해 흡수하여 식인 식물과 마수를 폭발적으로 자라나게 만들어 숲 영역을 넓힙니다.',
    quote: '섹터 7의 숲 그 자체, 인간 혐오자.',
    secretDetails: {
      revealedName: '잭',
      trueIdentity: '인간의 추악함을 알아버리고, 식물이 되길 택하다.',
      backstory: '원래는 숲과 동물을 사랑하던 수호자였습니다. 식물들의 이야기를 듣게 된 순간 식물들에게 인간들의 모든 추악함을 듣게 되었고, 타락하였습니다..'
    }
  },
  {
    id: 'jade',
    name: '제이드',
    gender: '남',
    rating: '엡실론 하위',
    personality: ['정중함', '배려심', '과묵'],
    role: '뱅가드 섹터 7 지부장 (1급 대원) / 정원사의 마지막 친구',
    sectorId: 7,
    addonName: '거목을 불사르는 불씨 - 흑련화(黑淵火)',
    addonDescription: '상대의 무효화 장벽이나 구조를 불문하고, 접촉 시 즉각 태워 없애버리는 기괴한 검은 불꽃입니다.',
    quote: '섹터 7의 수문장, 한때 정원사의 친구.',
  },
  {
    id: 'jester',
    name: '제스터',
    gender: '?',
    rating: '오메가 중위',
    personality: ['유쾌', '쾌활', '능글'],
    role: '섹터 8 킹 / 마스터 / 광기 어린 지휘자',
    sectorId: 8,
    addonName: '광기의 서곡 - 두란테 (Durante)',
    addonDescription: '공중에 오색의 가상 악보를 소출하여 물리 탄막을 발사하고 관객들의 신경을 자극하는 소리 광역 제어 능력입니다.',
    quote: '도시를 환락으로 이끄는 광대.',
    secretDetails: {
      revealedName: '미나',
      trueIdentity: '마을의 무능력자 소녀',
      backstory: '제스터의 정체는 대인공포증을 앓고 있는 소심한 소녀 미나입니다. 익스터널로 변한 것이며 애드온 자체는 미나의 것이기에 미나도 사용 가능합니다.'
    }
  },
  {
    id: 'mina',
    name: '미나',
    gender: '여',
    rating: '없음',
    personality: ['소심', '음침', '대인기피'],
    role: '섹터 8의 무능력자 주민',
    sectorId: 8,
    quote: '섹터 8의 \'평범한\' 무능력자 소녀.',
    secretDetails: {
      revealedName: '제스터',
      trueIdentity: '제스터의 가면 뒤 본모습',
      hiddenExternalName: '동경하는 나 - 맨 인 더 미러 (Man in the Mirror)',
      hiddenExternalDescription: '자신의 이상향인 환상적 대광대 제스터로 육신을 완전히 변신시키는 도구입니다.',
      backstory: '대인공포증이 극심해 타인과의 대화조차 겁내지만, 모두를 즐겁게 하고 싶다는 열망과 대인기피의 극복을 위해 마스터급 광대 제스터로 변신해 활동 중입니다.'
    }
  },
  {
    id: 'vengeance',
    name: '벤젠스',
    gender: '남',
    rating: '감마 중위',
    personality: ['유쾌', '능글', '능청'],
    role: '뱅가드 섹터 8 지부 3급 대원 / 사격 마스터',
    sectorId: 8,
    addonName: '6발의 마탄과 1발의 흉탄 - 디어 프라이시츠 (Der Freischütz)',
    addonDescription: '추적 명중하는 6발의 청색 마탄과, 임의의 위치를 관통 저격하는 1발의 적색 흉탄을 쏘는 푸른 리볼버를 발현합니다.',
    quote: '전문직 땡땡이 뱅가드 대원',
  },
  {
    id: 'lacaren',
    name: '라카렌',
    gender: '여',
    rating: '베타 중위',
    personality: ['가식적', '귀여움', '염세적'],
    role: '섹터 8 최고 인기 스트리머 겸 메가 인플루언서',
    sectorId: 8,
    addonName: '작은 세상의 주인 - 팜므파탈 (Femme Fatale)',
    addonDescription: '반경 50m 이내의 조명, 기후, 음향을 원하는 대로 변환하여 화려한 CG 가상 무대를 투사합니다.',
    quote: '온오프가 확실한 방송인',
  },
  {
    id: 'leky',
    name: '레키',
    gender: '여',
    rating: '엡실론 하위',
    personality: ['무심', '무뚝뚝', '피로'],
    role: '섹터 9 킹 / 의사',
    sectorId: 9,
    addonName: '영원이라는 이름의 절망 - 임모탈리타 (Immortalità)',
    addonDescription: '육신과 정신이 완전히 붕괴하더라도 즉시 이전 최상의 상태로 강제 회복을 집행하는 절대적 불사 능력입니다.',
    externalName: '나를 베어 남을 먹이는 자비 - 에우카리스티아 (Eucharistia)',
    externalDescription: '자신의 생명력을 도시 전역에 지속적으로 뿌리는 목덜미의 장미 형태의 문신입니다..',
    quote: '섹터 9 부활의 원천, 불사자.',
    secretDetails: {
      revealedName: '레키',
      trueIdentity: '죽음을 찾는 자',
      backstory: '자신의 생명력을 나눠주는 것으로 빠르게 태워 죽고자 합니다. 불사의 삶에 지쳐버렸습니다.'
    }
  },
  {
    id: 'selezia',
    name: '세레지아',
    gender: '여',
    rating: '감마 중위',
    personality: ['고혹적', '매혹적', '친절'],
    role: '섹터 9 영구 거주자 / 쾌락의 구도자 / 상냥한 성인',
    sectorId: 9,
    addonName: '아름다운 장미에 핀 독가시 - 로자리아 (Rosaria)',
    addonDescription: '신경을 조율하는 가시넝굴을 생성합니다. 접촉한 대상과 고통 파형을 상호 동기화하고 배가하여 공유합니다.',
    quote: '섹터 9의 마조히스트',
  },
  {
    id: 'ren',
    name: '렌',
    gender: '여',
    rating: '오메가급 익스터널',
    personality: ['밝음', '쾌활', '말많음'],
    role: '제로 섹터 중심부에 있던 의문의 검',
    sectorId: 0,
    addonName: '어떤 검사의 미련 - 노스탤지어 (Nostalgia)',
    addonDescription: '잡고 명상 시 정지된 시공간에서 누군가와 대련하며, 대륙 최강 수준의 검술을 영혼과 근육에 완벽히 전수합니다.',
    quote: '제로 섹터에 꽂혀있던 의문의 검',
    secretDetails: {
      revealedName: '무명검사',
      trueIdentity: '무명검사의 유품이자 그 자체',
      backstory: '무명검사가 백뢰와 싸우고 동귀어진해 절명하는 순간, 생의 미련으로 만들어낸 무기입니다. 무명검사의 혼이 잠재되어 있으며 검술을 전부 배우면 무명검사로써의 기억을 전부 찾습니다.'
    }
  },
  {
    id: 'bayak',
    name: '바야크',
    gender: '남',
    rating: '오메가 상위',
    personality: ['과묵', '무뚝뚝', '전투광'],
    role: '마스터 / 방랑자',
    sectorId: 10,
    addonName: '세계를 가르는 적뢰 - 플라낙스 (Phalanx)',
    addonDescription: '핏빛 적색 뇌전을 형성합니다. 전격을 창끝에 집중하여 원자를 분쇄하거나, 스스로 번개로 전환되어 빛의 궤적으로 이동합니다.',
    quote: '홀로 방랑하는 전투광',
  },
  {
    id: 'cornix',
    name: '코르닉스',
    gender: '여',
    rating: '엡실론 중위',
    personality: ['냉철', '무뚝뚝', '허당'],
    role: '13대 "레이븐" / 제자 찾고 있음',
    sectorId: 5,
    addonName: '사냥의 밤 - 나이트폴 (Nightfall)',
    addonDescription: '그늘진 그림자 영역에 자신의 흔적과 기척을 감춰 동화시킵니다. 물리 은폐를 제외하곤 의미 없는 능력이기에 강함은 순수한 기량에서 나옵니다.',
    externalName: '사냥꾼의 운명 - 울토 (Ulto)',
    externalDescription: '약자를 향한 비열한 범죄가 자행될 때, 브로치의 두 눈이 붉게 물들며 타겟의 정확한 위치와 정보를 뇌리에 직접 전사합니다.',
    quote: '13대 레이븐, 자신의 뜻을 이을 제자를 찾는 중.',
  }
];
